### ISSUE TITLE
when i run inference.py, i got this issues

### ISSUE THREAD

**Issue by cl886699** [thatbrguy/Pedestrian-Detector#1]
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\ProgramData\Anaconda3\envs\tensorflow\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Pedestrian-Detector-master\object_detection\inference.py", line 55, in feed
    TEST_IMAGE_PATHS, RESULT_IMAGE_PATHS, _ = load_details(args)
NameError: name 'args' is not defined

this is my code:
python object_detection/inference.py 
--input_dir=test_images
--output_dir=test_result
--label_map=annotations/label_map.pbtxt 
--frozen_graph=object_detection/pedestrian_pb/frozen_inference_graph.pb
--num_output_classes=1 
--n_jobs=1 
--delay=0
i do not knwo how to fix it , could you help me

**Comment by thatbrguy** [comment]
Fixed the issue. Give it a try after you pull the changes (Or clone the repo again).
